<?php

use Illuminate\Database\Seeder;
use Uatfinfra\ModelAutomotores\Vehiculo;

class VehiculoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //factory(Uatfinfra\ModelAutomotores\Vehiculo::class, 30)->create();

        $vehi = new Vehiculo;
        $vehi->tipo           = "Omnibus";
        $vehi->placa          = "3856-ZTH";
        $vehi->color          = "Blanco Combinado";
		$vehi->pasajeros      = "45 - 47";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "B270F";
        $vehi->kilometraje    = "26497";
        $vehi->marca          = "Volvo";
        $vehi->chasis         = "9BVT5T523FE403325";
        $vehi->motor          = "F1A075817";
        $vehi->cilindrada     = "7200";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 10;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Omnibus";
        $vehi->placa          = "3856-ZRB";
        $vehi->color          = "Blanco Combinado";
		$vehi->pasajeros      = "45 - 47";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "B270F";
        $vehi->kilometraje    = "25741";
        $vehi->marca          = "Volvo";
        $vehi->chasis         = "9BVT5T521FE403324";
        $vehi->motor          = "F1A075777";
        $vehi->cilindrada     = "7200";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 7;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RKU";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "29318";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09830";
        $vehi->motor          = "FE6232169C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 11;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RIR";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "32168";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09831";
        $vehi->motor          = "FE6232171C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 8;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RFE";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "29341";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09877";
        $vehi->motor          = "FE6232286C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 12;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RGH";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "29366";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09819";
        $vehi->motor          = "FE6232135C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 6;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RHL";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "34459";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09837";
        $vehi->motor          = "FE6232190C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 9;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RDX";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "32168";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09828";
        $vehi->motor          = "FE6232159C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 15;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-REB";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "23426";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09820";
        $vehi->motor          = "FE6232141C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 13;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RCS";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "1000";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09826";
        $vehi->motor          = "FE6232153C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 14;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RLA";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "17975";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09829";
        $vehi->motor          = "FE6232160C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 16;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "3981-RBN";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "37 - 39";
		$vehi->modelo         = "2015";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "28599";
        $vehi->marca          = "UD solo";
        $vehi->chasis         = "MKB210F09827";
        $vehi->motor          = "FE6232157C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 18;
		$vehi->save();


		$vehi = new Vehiculo;
        $vehi->tipo           = "Buss MKB210";
        $vehi->placa          = "1925-ZYC";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "41 - 43";
		$vehi->modelo         = "2008";
        $vehi->especificacion = "MKB210";
        $vehi->kilometraje    = "215792";
        $vehi->marca          = "Nissan";
        $vehi->chasis         = "MKB210F07629";
        $vehi->motor          = "FE6225354C";
        $vehi->cilindrada     = "6925";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Buss";
        $vehi->user_id        = 17;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Omnibus";
        $vehi->placa          = "3825-SPU";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "27 - 29";
		$vehi->modelo         = "2014";
        $vehi->especificacion = "DW9 solo";
        $vehi->kilometraje    = "19316";
        $vehi->marca          = "Mercedes Benz";
        $vehi->chasis         = "9BM688277DB881678";
        $vehi->motor          = "904957U1027647";
        $vehi->cilindrada     = "4200";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Civilian";
        $vehi->user_id        = 14;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Omnibus";
        $vehi->placa          = "3825-SKH";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "27 - 29";
		$vehi->modelo         = "2014";
        $vehi->especificacion = "DW9 solo";
        $vehi->kilometraje    = "22076";
        $vehi->marca          = "Mercedes Benz";
        $vehi->chasis         = "9BM688277DB881467";
        $vehi->motor          = "904957U1027534";
        $vehi->cilindrada     = "4200";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Civilian";
        $vehi->user_id        = 11;
		$vehi->save();


		$vehi = new Vehiculo;
        $vehi->tipo           = "Omnibus";
        $vehi->placa          = "3825-SFS";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "27 - 29";
		$vehi->modelo         = "2014";
        $vehi->especificacion = "DW9 solo";
        $vehi->kilometraje    = "18421";
        $vehi->marca          = "Mercedes Benz";
        $vehi->chasis         = "9BM688277DB882013";
        $vehi->motor          = "904957U1028020";
        $vehi->cilindrada     = "4200";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Civilian";
        $vehi->user_id        = 6;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Omnibus";
        $vehi->placa          = "3825-SNR";
        $vehi->color          = "Rojo Combinado";
		$vehi->pasajeros      = "27 - 29";
		$vehi->modelo         = "2014";
        $vehi->especificacion = "DW9 solo";
        $vehi->kilometraje    = "18925";
        $vehi->marca          = "Mercedes Benz";
        $vehi->chasis         = "9BM688277DB881426";
        $vehi->motor          = "904957U1027330";
        $vehi->cilindrada     = "4200";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Civilian";
        $vehi->user_id        = 15;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "3027-TRL";
        $vehi->color          = "Blanco";
		$vehi->pasajeros      = "3";
		$vehi->modelo         = "2012";
        $vehi->especificacion = "Land Cruiser";
        $vehi->kilometraje    = "141961";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "JTEBU3FJ90K040012";
        $vehi->motor          = "1GR-A522316";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "RECTORADO";
        $vehi->user_id        = 19;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "1483-TBL";
        $vehi->color          = "Blanco";
		$vehi->pasajeros      = "3";
		$vehi->modelo         = "2005";
        $vehi->especificacion = "Land Cruiser";
        $vehi->kilometraje    = "335153";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "JTECJO1J502001954";
        $vehi->motor          = "1FZ-0676196";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Vicerrectorado";
        $vehi->user_id        = 18;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "1756-KEU";
        $vehi->color          = "Negro";
		$vehi->pasajeros      = "6";
		$vehi->modelo         = "2003";
        $vehi->especificacion = "Land Cruiser";
        $vehi->kilometraje    = "252602";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "JTEBM29J400017416";
        $vehi->motor          = "3RZ3094224";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "1756-KDR";
        $vehi->color          = "Negro";
		$vehi->pasajeros      = "6";
		$vehi->modelo         = "2003";
        $vehi->especificacion = "Land Cruiser";
        $vehi->kilometraje    = "336115";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "JTEBM29J600017143";
        $vehi->motor          = "3RZ096163";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "1332-GSE";
        $vehi->color          = "Dorado";
		$vehi->pasajeros      = "8";
		$vehi->modelo         = "2002";
        $vehi->especificacion = "Patrol";
        $vehi->kilometraje    = "0";
        $vehi->marca          = "Nissan";
        $vehi->chasis         = "JN1TFSY61Z0530098";
        $vehi->motor          = "TB48008544";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "1042-KBG";
        $vehi->color          = "Guindo";
		$vehi->pasajeros      = "8";
		$vehi->modelo         = "1994";
        $vehi->especificacion = "Patrol";
        $vehi->kilometraje    = "258900";
        $vehi->marca          = "Nissan";
        $vehi->chasis         = "WGY60130273";
        $vehi->motor          = "TB42100216";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "1332-GRB";
        $vehi->color          = "Rojo";
		$vehi->pasajeros      = "8";
		$vehi->modelo         = "2002";
        $vehi->especificacion = "Patrol";
        $vehi->kilometraje    = "253494";
        $vehi->marca          = "Nissan";
        $vehi->chasis         = "JN1TFSY61Z0530255";
        $vehi->motor          = "TB4800994";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Camioneta";
        $vehi->placa          = "1756-KIK";
        $vehi->color          = "Plomo Plateado";
		$vehi->pasajeros      = "6";
		$vehi->modelo         = "2003";
        $vehi->especificacion = "Hilux";
        $vehi->kilometraje    = "259018";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "JTFDM626700029089";
        $vehi->motor          = "3RZ3099770";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Camioneta";
        $vehi->placa          = "1343-LRC";
        $vehi->color          = "Rojo Mica";
		$vehi->pasajeros      = "6";
		$vehi->modelo         = "1998";
        $vehi->especificacion = "Hilux";
        $vehi->kilometraje    = "282652";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "RZN1690004671";
        $vehi->motor          = "3RZ-1721155";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Camioneta";
        $vehi->placa          = "1343-LPY";
        $vehi->color          = "Rojo Mica";
		$vehi->pasajeros      = "6";
		$vehi->modelo         = "1998";
        $vehi->especificacion = "Hilux";
        $vehi->kilometraje    = "184539";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "RZN169L-0004648";
        $vehi->motor          = "3RZ1722248";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Automovil";
        $vehi->placa          = "855-XEA";
        $vehi->color          = "Azul";
		$vehi->pasajeros      = "4";
		$vehi->modelo         = "1998";
        $vehi->especificacion = "Lancer";
        $vehi->kilometraje    = "102490";
        $vehi->marca          = "Mitsubishi";
        $vehi->chasis         = "JMYSNCK1AVU007227";
        $vehi->motor          = "4G13TQ1595";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Camión";
        $vehi->placa          = "577-GCG";
        $vehi->color          = "Azul";
		$vehi->pasajeros      = "3";
		$vehi->modelo         = "1993";
        $vehi->especificacion = "Mercedes Benz";
        $vehi->kilometraje    = "0";
        $vehi->marca          = "912";
        $vehi->chasis         = "9BM6881123PB-975122";
        $vehi->motor          = "37495010186201";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Camioneta";
        $vehi->placa          = "2558-LTC";
        $vehi->color          = "Verde";
		$vehi->pasajeros      = "4";
		$vehi->modelo         = "2011";
        $vehi->especificacion = "Frontier";
        $vehi->kilometraje    = "100";
        $vehi->marca          = "Marca";
        $vehi->chasis         = "ninguno3";
        $vehi->motor          = "ninguno3";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "1343-LNT";
        $vehi->color          = "Azul Oscuro";
		$vehi->pasajeros      = "4";
		$vehi->modelo         = "1998";
        $vehi->especificacion = "Land Cruiser";
        $vehi->kilometraje    = "100";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "ninguno2";
        $vehi->motor          = "ninguno2";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Ciudad";
        $vehi->user_id        = 0;
		$vehi->save();

		$vehi = new Vehiculo;
        $vehi->tipo           = "Vagoneta";
        $vehi->placa          = "PKA-093";
        $vehi->color          = "Rojo";
		$vehi->pasajeros      = "4";
		$vehi->modelo         = "1995";
        $vehi->especificacion = "Jeep";
        $vehi->kilometraje    = "100";
        $vehi->marca          = "Toyota";
        $vehi->chasis         = "ninguno1";
        $vehi->motor          = "ninguno1";
        $vehi->cilindrada     = "0";
        $vehi->estado         = "ÓPTIMO";
        $vehi->valor          = "Sub sede";
        $vehi->user_id        = 0;
		$vehi->save();

    }
}
